# -*- coding: utf-8 -*-
"""Automation_DB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ZfgIRXCaJHJ6ZDTyKd54VaRt4PjgCeN

#Automation Code using Device_control Table

##Import functies
"""

import atexit
import time
from datetime import datetime, timedelta

import pytz
import requests
import psycopg2
from psycopg2.pool import SimpleConnectionPool
from gpiozero import Motor, Button, LED, DigitalOutputDevice #kan niet in google collab opgehaald worden

from typing import Optional, Tuple, Dict, Any

"""##Communicatie met DB"""

DATABASE_URL = "postgresql://postgres.qdwofrcncjnhstbqegnj:Vg4Zc6Z!_tLKtMj@aws-1-eu-west-1.pooler.supabase.com:6543/postgres"

_pool = psycopg2.pool.SimpleConnectionPool(minconn=1, maxconn=5, dsn=DATABASE_URL)

print("[DB] Connected")

atexit.register(lambda: _pool.closeall() if _pool and not _pool.closed else None)

def get_db_connection():
    return _pool.getconn()

def release_db_connection(conn):
    _pool.putconn(conn)

"""##System Settings"""

LATITUDE = 50.88
LONGITUDE = 4.70
LOCAL_TZ = pytz.timezone("Europe/Brussels")
POLL_SECONDS = 5
DOOR_TIMEOUT_SECONDS = 70
FEEDER_OPEN_SECONDS = 8
FEEDER_CLOSE_SECONDS = 8

DOOR_OPEN_OFFSET_MIN = -10      # 10 min voor zonsopgang
DOOR_CLOSE_OFFSET_MIN = 30      # 30 min na zonsondergang

FEEDER_OPEN_OFFSET_MIN = 0      # bv. open vanaf zonsopgang
FEEDER_CLOSE_OFFSET_MIN = 0     # bv. dicht vanaf zonsondergang

BACKUP_SUNRISE_HOUR = 7
BACKUP_SUNRISE_MINUTE = 30
BACKUP_SUNSET_HOUR = 18
BACKUP_SUNSET_MINUTE = 0

VALID_UPDATE_COLUMNS = {
    "fan_auto", "fan_speed_pct", "fan_override_pct", "fan_status_pct",
    "door_auto", "door_target", "door_status",
    "feeder_auto", "feeder_target", "feeder_status",
}

LAST_VALID_SUN_TIMES = {
    "sunrise": None,
    "sunset": None,
}

# Verwachte statuses/targets
VALID_DOOR_TARGETS = {"open", "closed"}
VALID_FEEDER_TARGETS = {"open", "closed"}
VALID_DOOR_STATUSES = {"open", "closed", "moving", "error"}
VALID_FEEDER_STATUSES = {"open", "closed", "moving", "error"}

"""##Setup connections components"""

# GPIO
# Door on H-bridge B
door_motor = Motor(forward=18, backward=19)
switch_bottom = Button(17)
switch_top = Button(27)

# Feeder on free pins
feeder_motor = Motor(forward=20, backward=21)

# Fan on H-bridge A, no reverse
fan_in1 = DigitalOutputDevice(23)
fan_in2 = DigitalOutputDevice(24)

predator_led = LED(22)

DEVICE_CONTROL_SQL = """
CREATE TABLE IF NOT EXISTS device_control (
    id INTEGER PRIMARY KEY,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fan_auto BOOLEAN DEFAULT TRUE,
    fan_speed_pct FLOAT DEFAULT 0,
    fan_override_pct FLOAT,
    fan_status_pct FLOAT DEFAULT 0,
    door_auto BOOLEAN DEFAULT TRUE,
    door_target TEXT DEFAULT 'open',
    door_status TEXT DEFAULT 'closed',
    feeder_auto BOOLEAN DEFAULT TRUE,
    feeder_target TEXT DEFAULT 'open',
    feeder_status TEXT DEFAULT 'closed'
);
"""

"""##Setup Function (all setup in one function)"""

def init_db():
    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(DEVICE_CONTROL_SQL)
            cur.execute("SELECT id FROM device_control WHERE id = 1")
            if cur.fetchone() is None:
                cur.execute("""
                    INSERT INTO device_control
                    (id, fan_auto, fan_speed_pct, fan_override_pct, fan_status_pct,
                     door_auto, door_target, door_status,
                     feeder_auto, feeder_target, feeder_status)
                    VALUES (1, TRUE, 0, NULL, 0, TRUE, 'open', 'closed', TRUE, 'open', 'closed')
                """)
        conn.commit()
        print("[DB] device_control klaar")
    except Exception as e:
        conn.rollback()
        print(f"[DB] init fout: {e}")
        raise
    finally:
        release_db_connection(conn)


def cleanup():
    print("[MAIN] cleanup start")
    try:
        stop_door()
    except Exception:
        pass
    try:
        stop_feeder()
    except Exception:
        pass
    try:
        fan_off()
    except Exception:
        pass
    try:
        predator_led.off()
    except Exception:
        pass
    print("[MAIN] cleanup klaar")


def setup():
    print("[MAIN] setup start")

    # 1. Database en control table klaarzetten
    init_db()

    # 2. Hardware in veilige beginstand zetten
    stop_door()
    stop_feeder()
    fan_off()
    predator_led.off()

    # 3. Eerste synchronisatie van deurstatus op basis van switches
    try:
        sync_door_status_from_switches()
    except Exception as e:
        print(f"[MAIN] kon deurstatus niet initialiseren: {e}")

    # 4. Eerste fan-status veilig initialiseren
    try:
        update_status(fan_status_pct=0)
    except Exception as e:
        print(f"[MAIN] kon fan_status_pct niet initialiseren: {e}")

    print("[MAIN] setup klaar")

"""##nieuwe functies (verbeterde versie met fout herstel + backup loops)"""

def fetch_control() -> Optional[dict]:
    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT * FROM device_control WHERE id = 1")
            row = cur.fetchone()
            if row is None:
                return None
            cols = [d.name for d in cur.description]
            return dict(zip(cols, row))
    finally:
        release_db_connection(conn)


def update_status(**kwargs) -> bool:
    if not kwargs:
        return False

    invalid = [k for k in kwargs if k not in VALID_UPDATE_COLUMNS]
    if invalid:
        print(f"[DB] Ongeldige kolommen in update_status: {invalid}")
        return False

    cols = ", ".join([f"{k} = %s" for k in kwargs])
    vals = list(kwargs.values())
    vals.append(1)

    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(
                f"UPDATE device_control SET {cols}, updated_at = CURRENT_TIMESTAMP WHERE id = %s",
                vals
            )
        conn.commit()
        return True
    except Exception as e:
        conn.rollback()
        print(f"[DB] Update fout: {e}")
        return False
    finally:
        release_db_connection(conn)


def _fixed_backup_sun_times() -> Tuple[datetime, datetime]:
    now = datetime.now(LOCAL_TZ)
    sunrise = now.replace(
        hour=BACKUP_SUNRISE_HOUR,
        minute=BACKUP_SUNRISE_MINUTE,
        second=0,
        microsecond=0
    )
    sunset = now.replace(
        hour=BACKUP_SUNSET_HOUR,
        minute=BACKUP_SUNSET_MINUTE,
        second=0,
        microsecond=0
    )
    return sunrise, sunset


def get_sun_times() -> Tuple[datetime, datetime]:
    try:
        url = f"https://api.sunrise-sunset.org/json?lat={LATITUDE}&lng={LONGITUDE}&formatted=0"
        response = requests.get(url, timeout=10)
        response.raise_for_status()

        payload = response.json()
        results = payload["results"]

        sunrise = datetime.fromisoformat(results["sunrise"].replace("Z", "+00:00")).astimezone(LOCAL_TZ)
        sunset = datetime.fromisoformat(results["sunset"].replace("Z", "+00:00")).astimezone(LOCAL_TZ)

        LAST_VALID_SUN_TIMES["sunrise"] = sunrise
        LAST_VALID_SUN_TIMES["sunset"] = sunset

        return sunrise, sunset

    except Exception as e:
        print(f"[SUN] API fout: {e}")

        if LAST_VALID_SUN_TIMES["sunrise"] and LAST_VALID_SUN_TIMES["sunset"]:
            print("[SUN] Gebruik laatst geldige sunrise/sunset")
            return LAST_VALID_SUN_TIMES["sunrise"], LAST_VALID_SUN_TIMES["sunset"]

        print("[SUN] Gebruik vaste backup sunrise/sunset")
        return _fixed_backup_sun_times()




def stop_door():
    door_motor.stop()


def stop_feeder():
    feeder_motor.stop()


def fan_on():
    fan_in1.on()
    fan_in2.off()


def fan_off():
    fan_in1.off()
    fan_in2.off()





def sync_door_status_from_switches():
    top = switch_top.is_pressed
    bottom = switch_bottom.is_pressed

    if top and bottom:
        update_status(door_status="error")
        return "error"
    elif top:
        update_status(door_status="open")
        return "open"
    elif bottom:
        update_status(door_status="closed")
        return "closed"
    else:
        return None


def validate_row(row: dict) -> bool:
    if row is None:
        print("[MAIN] Geen control row gevonden")
        return False

    if row["door_target"] not in VALID_DOOR_TARGETS:
        print(f"[MAIN] Ongeldige door_target: {row['door_target']}")
        update_status(door_status="error")
        return False

    if row["feeder_target"] not in VALID_FEEDER_TARGETS:
        print(f"[MAIN] Ongeldige feeder_target: {row['feeder_target']}")
        update_status(feeder_status="error")
        return False

    if row["door_status"] not in VALID_DOOR_STATUSES:
        print(f"[MAIN] Ongeldige door_status: {row['door_status']}")
        update_status(door_status="error")
        return False

    if row["feeder_status"] not in VALID_FEEDER_STATUSES:
        print(f"[MAIN] Ongeldige feeder_status: {row['feeder_status']}")
        update_status(feeder_status="error")
        return False

    return True




def open_door() -> bool:
    print("[DOOR] openen")

    if switch_top.is_pressed:
        stop_door()
        update_status(door_status="open")
        print("[DOOR] al open")
        return True

    update_status(door_status="moving")
    start = time.monotonic()
    door_motor.forward(1)

    try:
        while not switch_top.is_pressed:
            if switch_bottom.is_pressed and time.monotonic() - start > 1:
                pass

            if time.monotonic() - start > DOOR_TIMEOUT_SECONDS:
                print("[DOOR] timeout bij openen")
                stop_door()
                update_status(door_status="error")
                return False

            time.sleep(0.02)

        stop_door()
        update_status(door_status="open")
        print("[DOOR] open")
        return True

    except Exception as e:
        stop_door()
        update_status(door_status="error")
        print(f"[DOOR] fout bij openen: {e}")
        return False


def close_door() -> bool:
    print("[DOOR] sluiten")

    if switch_bottom.is_pressed:
        stop_door()
        update_status(door_status="closed")
        print("[DOOR] al closed")
        return True

    update_status(door_status="moving")
    start = time.monotonic()
    door_motor.backward(1)

    try:
        while not switch_bottom.is_pressed:
            if time.monotonic() - start > DOOR_TIMEOUT_SECONDS:
                print("[DOOR] timeout bij sluiten")
                stop_door()
                update_status(door_status="error")
                return False

            time.sleep(0.02)

        stop_door()
        update_status(door_status="closed")
        print("[DOOR] closed")
        return True

    except Exception as e:
        stop_door()
        update_status(door_status="error")
        print(f"[DOOR] fout bij sluiten: {e}")
        return False






def feeder_open() -> bool:
    print("[FEEDER] openen")

    if fetch_control()["feeder_status"] == "open":
        stop_feeder()
        return True

    update_status(feeder_status="moving")
    feeder_motor.forward(1)

    try:
        time.sleep(FEEDER_OPEN_SECONDS)
        stop_feeder()
        update_status(feeder_status="open")
        print("[FEEDER] open")
        return True
    except Exception as e:
        stop_feeder()
        update_status(feeder_status="error")
        print(f"[FEEDER] fout bij openen: {e}")
        return False


def feeder_close() -> bool:
    print("[FEEDER] sluiten")

    if fetch_control()["feeder_status"] == "closed":
        stop_feeder()
        return True

    update_status(feeder_status="moving")
    feeder_motor.backward(1)

    try:
        time.sleep(FEEDER_CLOSE_SECONDS)
        stop_feeder()
        update_status(feeder_status="closed")
        print("[FEEDER] closed")
        return True
    except Exception as e:
        stop_feeder()
        update_status(feeder_status="error")
        print(f"[FEEDER] fout bij sluiten: {e}")
        return False





def set_fan_pct(pct):
    try:
        pct = max(0, min(100, float(pct)))
    except Exception:
        pct = 0

    if pct <= 0:
        fan_off()
    else:
        fan_on()

    update_status(fan_status_pct=pct)


def compute_fan_target(row):
    if row["fan_auto"]:
        return row["fan_speed_pct"] if row["fan_speed_pct"] is not None else 0
    return row["fan_override_pct"] if row["fan_override_pct"] is not None else 0




def compute_door_target(row, door_open_time, door_close_time) -> str:
    now = datetime.now(LOCAL_TZ)

    if row["door_auto"]:
        if now >= door_close_time:
            return "closed"
        elif now >= door_open_time:
            return "open"
        else:
            return "closed"

    return row["door_target"]


def compute_feeder_target(row, feeder_open_time, feeder_close_time) -> str:
    now = datetime.now(LOCAL_TZ)

    if row["feeder_auto"]:
        if feeder_open_time <= now < feeder_close_time:
            return "open"
        return "closed"

    return row["feeder_target"]





def apply_door_state(row, door_open_time, door_close_time):
    desired = compute_door_target(row, door_open_time, door_close_time)

    if row["door_auto"] and row["door_target"] != desired:
        update_status(door_target=desired)

    status = row["door_status"]

    if status == "error":
        print("[DOOR] status is error, geen automatische actie")
        return

    if desired == status:
        return

    if desired == "open":
        open_door()
    elif desired == "closed":
        close_door()


def apply_feeder_state(row, feeder_open_time, feeder_close_time):
    desired = compute_feeder_target(row, feeder_open_time, feeder_close_time)

    if row["feeder_auto"] and row["feeder_target"] != desired:
        update_status(feeder_target=desired)

    status = row["feeder_status"]

    if status == "error":
        print("[FEEDER] status is error, geen automatische actie")
        return

    if desired == status:
        return

    if desired == "open":
        feeder_open()
    elif desired == "closed":
        feeder_close()

"""##Main loop automation (met verbeterde code)"""

def main_loop():
    print("[MAIN] start automation loop")

    while True:
        try:
            sync_door_status_from_switches()

            row = fetch_control()
            if not validate_row(row):
                time.sleep(POLL_SECONDS)
                continue

            sunrise, sunset = get_sun_times()

            door_open_time = sunrise + timedelta(minutes=DOOR_OPEN_OFFSET_MIN)
            door_close_time = sunset + timedelta(minutes=DOOR_CLOSE_OFFSET_MIN)

            feeder_open_time = sunrise + timedelta(minutes=FEEDER_OPEN_OFFSET_MIN)
            feeder_close_time = sunset + timedelta(minutes=FEEDER_CLOSE_OFFSET_MIN)

            apply_door_state(row, door_open_time, door_close_time)
            apply_feeder_state(row, feeder_open_time, feeder_close_time)

            fan_target = compute_fan_target(row)
            set_fan_pct(fan_target)

        except Exception as e:
            print(f"[MAIN] onverwachte fout: {e}")

        time.sleep(POLL_SECONDS)

"""##Final loop automation"""

def run():
    try:
        setup()
        main_loop()
    except KeyboardInterrupt:
        print("[MAIN] handmatig gestopt")
    except Exception as e:
        print(f"[MAIN] error: {e}")
        raise
    finally:
        cleanup()

if __name__ == "__main__":
    run()

"""#Oude Functies + loop (versie 1)

##Functies automation acties
"""

# @title
def get_sun_times() -> Tuple[datetime, datetime]:
    try:
        url = f"https://api.sunrise-sunset.org/json?lat={LATITUDE}&lng={LONGITUDE}&formatted=0"
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()["results"]

        sunrise = datetime.fromisoformat(data["sunrise"].replace("Z", "+00:00")).astimezone(LOCAL_TZ)
        sunset = datetime.fromisoformat(data["sunset"].replace("Z", "+00:00")).astimezone(LOCAL_TZ)

        # Normaliseer naar vandaag
        today = datetime.now(LOCAL_TZ).date()
        sunrise = sunrise.replace(date=today)
        sunset = sunset.replace(date=today)

        return sunrise, sunset

        #backup als ophalen api niet lukt
    except Exception as e:
        print(f"[SUN] API fout: {e}, gebruik backup tijden")
        today = datetime.now(LOCAL_TZ).date()
        backup_sunrise = BACKUP_SUNRISE.replace(date=today)
        backup_sunset = BACKUP_SUNSET.replace(date=today)
        return backup_sunrise, backup_sunset

def fetch_control():
    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT * FROM device_control WHERE id = 1")
            row = cur.fetchone()
            cols = [d.name for d in cur.description]
            return dict(zip(cols, row))
    finally:
        release_db_connection(conn)

def update_status(**kwargs) -> bool:
    """Update velden veilig met foutafhandeling."""
    if not kwargs:
        return False

    cols = ", ".join([f"{k} = %s" for k in kwargs])
    vals = list(kwargs.values())
    vals.append(1)

    conn = get_db_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(f"UPDATE device_control SET {cols}, updated_at = CURRENT_TIMESTAMP WHERE id = %s", vals)
        conn.commit()
        return True
    except Exception as e:
        print(f"[DB] Update fout: {e}")
        conn.rollback()
        return False
    finally:
        release_db_connection(conn)

def stop_door():
    door_motor.stop()

def stop_feeder():
    feeder_motor.stop()

def open_door():
    print("[DOOR] openen")
    update_status(door_status='moving')
    start = time.monotonic()
    door_motor.forward(1)
    while not switch_top.is_pressed:
        if time.monotonic() - start > DOOR_TIMEOUT_SECONDS: #zorgt dat de deur niet te lang blijft werken (als het langer dan de timout tijd bezig is stopt het automatisch)
            print("[DOOR] timeout bij openen")
            break
        time.sleep(0.02) #zorgt dat de code niet meteen verder doet en de CPU beetje bespaart blijft
    stop_door()
    update_status(door_status='open')
    print("[DOOR] open")

def close_door():
    print("[DOOR] sluiten")
    update_status(door_status='moving')
    start = time.monotonic()
    door_motor.backward(1)
    while not switch_bottom.is_pressed:
        if time.monotonic() - start > DOOR_TIMEOUT_SECONDS:
            print("[DOOR] timeout bij sluiten")
            break
        time.sleep(0.02)
    stop_door()
    update_status(door_status='closed')
    print("[DOOR] closed")

def feeder_open():
    print("[FEEDER] openen")
    update_status(feeder_status='moving')
    feeder_motor.forward(1)
    time.sleep(FEEDER_OPEN_SECONDS)
    stop_feeder()
    update_status(feeder_status='open')
    print("[FEEDER] open")

def feeder_close():
    print("[FEEDER] sluiten")
    update_status(feeder_status='moving')
    feeder_motor.backward(1)
    time.sleep(FEEDER_CLOSE_SECONDS) #zorgt dat de motor de juiste tijd werkt voor het stopt
    stop_feeder()
    update_status(feeder_status='closed')
    print("[FEEDER] closed")

def fan_on():
    fan_in1.on()
    fan_in2.off()

def fan_off():
    fan_in1.off()
    fan_in2.off()

def set_fan_pct(pct):
    pct = max(0, min(100, float(pct)))
    if pct <= 0:
        fan_off()
    else:
        fan_on()
    update_status(fan_status_pct=pct)

def compute_fan_target(row):
  #eerst kijk je of de fan auto = True => ja dan doe je gwn fan_pct
  #is fan auto = false => dan doe je manual override met de kolom fan_override_pct
  #als de fan_override = 0/None is dan doe je de fan uit
    if row['fan_auto']:
        return row['fan_speed_pct']
    return row['fan_override_pct'] if row['fan_override_pct'] is not None else 0

def apply_door_state(row, door_open_time, door_close_time):
  #staat auto van door op => dan bepaald de tijd van zonsopgang/zonsondergang de target van de deur (open of closed)
  #de automatische target wordt ook naar de database teruggeschereven zodat er zeker is dat het gewoon de target leest
  #staat auto niet aan dan is het gewoon het uitvoeren van de target van de deur in de db door de gebruiker aan te passen

  #via de webiste moet je dus de auto kunnen afzetten en het target bepalen
    now = datetime.now(LOCAL_TZ)
    if row['door_auto']:
        if now >= door_close_time:
            desired = 'closed'
        elif now >= door_open_time:
            desired = 'open'
        else:
            desired = row['door_status']  # of behouden wat logisch is vóór opentijd
        if row['door_target'] != desired:
            update_status(door_target=desired)
    else:
        desired = row['door_target']

    status = row['door_status']

    if desired == status:
        return
    if desired == 'open':
        open_door()
    elif desired == 'closed':
        close_door()

def apply_feeder_state(row, feeder_open_time, feeder_close_time):
    #zelfde werkingsprincipe als door state
    now = datetime.now(LOCAL_TZ)
    if row['feeder_auto']:
        if feeder_open_time <= now < feeder_close_time:
            desired = 'open'
        else:
            desired = 'closed'
        if row['feeder_target'] != desired:
            update_status(feeder_target=desired)
    else:
        desired = row['feeder_target']

    status = row['feeder_status']

    if desired == status:
        return
    if desired == 'open':
        feeder_open()
    elif desired == 'closed':
        feeder_close()

"""##main loop versie 1 (simpele functies)"""

# @title
def main():
    init_db()
    sunrise, sunset = get_sun_times()
    last_sun_fetch_day = None
    door_open_time = sunrise - timedelta(minutes=DOOR_OPEN_OFFSET_MIN)
    door_close_time = sunset + timedelta(minutes=DOOR_CLOSE_OFFSET_MIN)
    print(f"[TIME] sunrise={sunrise.strftime('%H:%M')} sunset={sunset.strftime('%H:%M')}")
    try:
        while True:
            now = datetime.now(LOCAL_TZ)
            if last_sun_fetch_day != now.date():
                sunrise, sunset = get_sun_times()
                door_open_time = sunrise - timedelta(minutes=DOOR_OPEN_OFFSET_MIN)
                door_close_time = sunset + timedelta(minutes=DOOR_CLOSE_OFFSET_MIN)
                last_sun_fetch_day = now.date()
            row = fetch_control()
            apply_door_state(row, door_open_time, door_close_time)
            apply_feeder_state(row, sunrise, sunset)
            target_fan = compute_fan_target(row)
            set_fan_pct(target_fan)
            is_dark = now >= door_close_time or now < door_open_time
            if is_dark:
                predator_led.on()
            else:
                predator_led.off()
            print(f"[STATE] door={row['door_status']} feeder={row['feeder_status']} fan={target_fan}% auto_door={row['door_auto']} auto_feeder={row['feeder_auto']} auto_fan={row['fan_auto']}")
            time.sleep(POLL_SECONDS)
    except KeyboardInterrupt:
        print("[SYS] stoppen")
    finally:
        stop_door()
        stop_feeder()
        fan_off()
        predator_led.off()
        print("[SYS] GPIO veilig afgesloten")

if __name__ == '__main__':
    main()