# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iyqo_F7INeIH1eKPM4690Bnqp1z6tP_w
"""

import math

# constante

PI = math.pi

# afmetingen feeder
FEEDER_PIPE_INNER_DIAM   = 0.102      # m
FEEDER_PIPE_HEIGHT       = 0.973      # m
FEEDER_TRAY_DIAM         = 0.187      # m
FEEDER_TRAY_HEIGHT       = 0.035     # m

# maximum vulhoogte: 5 cm onder de bovenkant
FEEDER_MAX_FILL_HEIGHT   = FEEDER_PIPE_HEIGHT - 0.05   # m

# voorgecalculeerde straal en volumes
FEEDER_PIPE_RADIUS       = FEEDER_PIPE_INNER_DIAM / 2.0
FEEDER_PIPE_MAX_VOLUME   = PI * FEEDER_PIPE_RADIUS**2 * FEEDER_MAX_FILL_HEIGHT

FEEDER_TRAY_RADIUS       = FEEDER_TRAY_DIAM / 2.0
FEEDER_TRAY_VOLUME       = PI * FEEDER_TRAY_RADIUS**2 * FEEDER_TRAY_HEIGHT

#FEEDER_TOTAL_MAX_VOLUME  = FEEDER_PIPE_MAX_VOLUME + FEEDER_TRAY_VOLUME


# Drinker afmetingen
DRUM_BOTTOM_INNER_DIAM   = 0.208     # m
DRUM_TOP_INNER_DIAM      = 0.16      # m eerste meting bovenste rand was 0.137
DRUM_HEIGHT              = 0.205     # m

TRAY_TOP_innerDIAM       = 0.214     # m
TRAY_GUTTER_WIDTH        = 0.028     # m
TRAY_HEIGHT              = 0.034     # m
TRAY_OUTER_INNER_DIAM    = 0.278     # m

# maximum vulhoogte: 5 cm onder bovenkant
DRINKER_MAX_FILL_HEIGHT  = DRUM_HEIGHT - 0.03  # needs to be measured with the sensor (height sensor is 0.019)

# radii en frustum‑constanten (voor kegel)
DRUM_R_TOP   = DRUM_TOP_INNER_DIAM / 2.0
DRUM_R_BOT   = DRUM_BOTTOM_INNER_DIAM / 2.0

def volume_frustum(r1, r2, h):
    """Volume afgeknotte kegel."""
    return (PI * h / 3.0) * (r1*r1 + r1*r2 + r2*r2)

# volledig gevulde drum tot DRINKER_MAX_FILL_HEIGHT
DRUM_FULL_VOLUME = volume_frustum(DRUM_R_BOT,
                                  DRUM_R_BOT + (DRUM_R_TOP - DRUM_R_BOT) *
                                  (DRINKER_MAX_FILL_HEIGHT / DRUM_HEIGHT),
                                  DRINKER_MAX_FILL_HEIGHT)

# schotelvolume
TRAY_R_INNER = TRAY_TOP_innerDIAM / 2.0
TRAY_R_OUTER = TRAY_OUTER_INNER_DIAM / 2.0
TRAY_MAX_VOLUME = PI * (TRAY_R_OUTER**2 - TRAY_R_INNER**2) * TRAY_HEIGHT

# simpele aanname: bij voldoende water is de goot ongeveer halfvol
TRAY_NOMINAL_WATER_VOLUME = TRAY_MAX_VOLUME * 0.5

#DRINKER_TOTAL_MAX_VOLUME = DRUM_FULL_VOLUME + TRAY_NOMINAL_WATER_VOLUME


def feeder_status(distance_sensor_m):
    """
    distance_sensor_m: afstand van sensor (boven in buis) tot voeroppervlak (m).
    Retourneert (volume_m3, volume_liter, percentage_vol).
    """
    # hoogte voer in de buis, begrensd op [0, FEEDER_MAX_FILL_HEIGHT]
    feed_height = FEEDER_PIPE_HEIGHT - distance_sensor_m
    if feed_height < 0:
        feed_height = 0.0
    if feed_height > FEEDER_MAX_FILL_HEIGHT:
        feed_height = FEEDER_MAX_FILL_HEIGHT

    volume_pipe = PI * FEEDER_PIPE_RADIUS**2 * feed_height
    volume_total = volume_pipe #+ FEEDER_TRAY_VOLUME

    percent_full = (volume_total / FEEDER_PIPE_MAX_VOLUME) * 100.0
    return percent_full


def feeder_status_label(percent):
    """Convert feeder percentage to status string."""
    if percent > 70:
        return "full"
    elif percent > 30:
        return "normal"
    elif percent > 10:
        return "low"
    else:
        return "empty"


def drinker_status(distance_sensor_m):
    """
    distance_sensor_m: afstand van sensor (boven in drum) tot wateroppervlak (m).
    Retourneert (volume_m3, volume_liter, percentage_vol).
    """
    # waterhoogte, begrensd op [0, DRINKER_MAX_FILL_HEIGHT]
    water_height = DRUM_HEIGHT - distance_sensor_m
    if water_height < 0:
        water_height = 0.0
    if water_height > DRINKER_MAX_FILL_HEIGHT:
        water_height = DRINKER_MAX_FILL_HEIGHT

    if water_height == 0:
        volume_drum = 0.0
    else:
        # radius op waterniveau (lineaire interpolatie)
        z_water = DRUM_HEIGHT - water_height      # afstand vanaf boven
        r_water = DRUM_R_TOP + (DRUM_R_BOT - DRUM_R_TOP) * (z_water / DRUM_HEIGHT)

        # volume water = frustum tussen r_water en r_bottom
        volume_drum = volume_frustum(r_water, DRUM_R_BOT, water_height)

    volume_total = volume_drum #+ TRAY_NOMINAL_WATER_VOLUME
    percent_full = (volume_total / DRUM_FULL_VOLUME) * 100.0
    return percent_full


def drinker_status_label(percent):
    """Convert drinker percentage to status string."""
    if percent > 70:
        return "full"
    elif percent > 30:
        return "normal"
    elif percent > 10:
        return "low"
    else:
        return "empty"


# ── Test ─────────────────────────────────────────────────────────────────────
# Use distance values directly from the serial read — no DB query needed.
if __name__ == "__main__":
    distance_feeder  = 0.70   # m (test value)
    distance_drinker = 0.20   # m (test value)

    f_pct = feeder_status(distance_feeder)
    d_pct = drinker_status(distance_drinker)

    print(f"Feeder:  {f_pct:5.1f}% vol — {feeder_status_label(f_pct)}")
    print(f"Drinker: {d_pct:5.1f}% vol — {drinker_status_label(d_pct)}")

